config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"
  #get "/", to: "main#index"
  root "main#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account
  validates :body, presence: true, length: { minimum: 1, maximum: 278 }
  validates :publish_at, presence: true
  after_initialize do
    self.publish_at ||= 2.hours.from_now
  end

  def published?
    tweet_id?
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :twitter_accounts
  has_many :tweets
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "enter a valid email address earthling!" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path flash[:alert] = "Attention Earthling! You must be signed in to that!" if Current.user.nil?
  end
end

app/controllers/concerns/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      username: auth.info.nickname,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
    )
    redirect_to twitter_accounts_path
    flash[:notice] = "You have Successfully Connected Your Account My Very Best"
  end

  def auth
    auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/concerns/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path
    flash[:notice] = "Attention Earthling, You Have Succesfully Deleted Your Account - @#{@twitter_account.username}"
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      #send email notification
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path flash[:notice] = "If You are not trying to trick me My Very Best, an email would be sent to you to change your password"
  end

  def edit
    begin
      @user = User.find_signed(params[:token], purpose: "password_reset")
    rescue
      redirect_to root_path
      flash[:alert] = "Your token has expired My Dear, try again will you?"
    end
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path flash[:notice] = "My Very Best Your Passord Was Changed Successfully"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
before_action :require_user_logged_in!

def edit
end


def update
  if Current.user.update(password_params)
    redirect_to root_path flash[:notice] = "You have successfully updated your password Earthling!"
  else
    render :edit
  end

end

private

def password_params
  params.require(:user).permit(:password, :password_confirmation)
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
def new
  @user = User.new
end

def create
 @user = User.new(user_params)
 if @user.save
  session[:user_id] = @user.id
  flash[:notice] = "Successfully created Account."
  redirect_to root_path

 else
  flash[:alert] = "Something went wrong"
  render :new
 end
end

def user_params
  params.require(:user).permit(:email, :password, :password_confirmation)
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully Logged Out My Very Best!."
    redirect_to root_path
  end
  def new

  end
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
      flash[:notice] = "You are successfully logged in Earthling!"
    else
      flash[:alert] = "Your email or password is incorrect my very best"
      render :new
    end

  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path
      flash[:notice] = "Your Tweet has been updated successfully My Very Best. Why did you change your mind?"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
    flash[:notice] = "Your Tweet was successfully unscheduled My Very Best. Who threatened You?"
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path
      flash[:notice] = "Your Tweet has been scheduled successfully My Very Best"
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class = "container" >
	<div class = "d-flex align-items-center justify-content-center">
		<h3>About Us</h3>
	</div>
	<div>
		<p>My very Best, this web application will help you to schedule tweets to your twitter. Tweet while you sleep, how does it sound to you?</p>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Scheduler App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>



<%= render partial: "shared/navbar" %>
 <body>
 <div class = "container">
 <%= render partial: "shared/flash" %>
    <%= yield %>
 </body>
 </div>
</html>

app/views/main/index.html.erb
<div class = "d-flex align-items-center justify-content-center">
<h1>Welcome to Twitter Scheduler App My Very Best</h1>
</div>

<div class = "d-flex align-items-center justify-content-center">
<p>Using this Web App, you will be able to connect your twitter accounts and schedule your tweets</p>
</div>

<div class = "d-flex align-items-center justify-content-center">
<% if Current.user %>
<%= button_to "Click to Connect Your Twitter Account", "/auth/twitter", method: :post, class: "btn btn-primary mt-3", data: { turbo: false } %>
<% else %>

<%= link_to "Click to Sign Up", sign_up_path, class: "btn btn-primary mt-3", data: { turbo: false } %>
<% end %>
</div>

app/views/password_resets/edit.html.erb
<h2>Reset Your Password, Mine</h2>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
<% if form.object.errors.any?%>
  <div class="alert alert-danger alert-dismissable">
  <% form.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>
<% end %>
<div class = "mb-3">
    <div class = "mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "ifedan" %>
    </div>
    <div class = "mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "ifedan" %>
    </div>
    <div>
    <%= form.submit "Reset Password", class: "btn btn-primary", local:true, data: { turbo: false } %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h2>Have You Forgotten Your Password, Earthling?</h2>

<%= form_with url: password_reset_path do |form| %>
<div class = "mb-3">
    <%= form.label :email, local:true %>
    <%= form.text_field :email, class: "form-control", placeholder: "ifedan@gmail.com" %>
    </div>
     <div>
    <%= form.submit "Reset Password", class: "btn btn-primary", local:true, data: { turbo: false } %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<%if flash[:notice]%>
<div class = "alert alert-info mt-4" role = "alert">
<%= flash[:notice]%>
</div>
<%end%>

<%if flash[:alert]%>
<div class = "alert alert-warning mt-4" role = "alert">
<%= flash[:alert]%>
</div>
<%end%>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any?%>
	<div class="alert alert-danger alert-dismissable">
		<% form.object.errors.full_messages.each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
	<div class="container-fluid">
		<%= link_to "Danitex", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to "Tweets", tweets_path, class: "nav-link active" %>
				</li>
				<li class="nav-item">
					<%= link_to "About Us", about_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
				</li>
			</ul>
			<ul class = "navbar-nav ms-auto mb-2 mb-lg-0">
				<% if Current.user %>
					<li class="nav-item">
						<%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
					</li>
					<li class = "nav-item">
						<%= button_to "Sign Out Earthling", logout_path , method: :delete, class: "nav-link btn btn-outline-secondary" %>
					</li>
				<% else %>
					<li class = "nav-item">
						<%= link_to "Sign In", sign_in_path, class: "nav-link" %>
					</li>
					<li class = "nav-item">
						<%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
					</li>
				<% end %>
			</div>
		</div>
	</nav>

app/views/tweets/_form_edit.html.erb
<%= form_with model: @tweet do |form| %>
	<%= render "shared/form_errors", form: form %>
	<div class="mb-3">
		<%= form.label :twitter_account_id %>
		<%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
		<%= link_to "Connect Another Twitter Account My Very Best", "/auth/twitter", class: "btn btn-primary mt-3" %>
	</div>
	<div class="mb-3">
		<%= form.label :body %>
		<%= form.text_area :body, class: "form-control" %>
	</div>
	<div class="mb-3">
		<%= form.label :publish_at %>
		<div class = "form-control">
			<%= form.datetime_select :publish_at%>
		</div>
	</div>
	<%= form.button "Edit Your Scheduled Tweet", data: { turbo: false }, class: "btn btn-primary" %>
	<% if form.object.persisted? %>
		<%= link_to "Delete Tweet", tweet_path(@tweet), data: {turbo_method: :delete, turbo_confirm: 'Are you so shy?'}, class: "btn btn-outline-danger" %>
	<% end %>
<% end %>

app/views/tweets/_form_schedule.html.erb
<%= form_with model: @tweet do |form| %>
	<%= render "shared/form_errors", form: form %>
	<div class="mb-3">
		<%= form.label :twitter_account_id %>
		<%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
		<%= link_to "Connect Another Twitter Account My Very Best", "/auth/twitter", class: "btn btn-primary mt-3" %>
	</div>
	<div class="mb-3">
		<%= form.label :body %>
		<%= form.text_area :body, class: "form-control" %>
	</div>
	<div class="mb-3">
		<%= form.label :publish_at %>
		<div class = "form-control">
			<%= form.datetime_select :publish_at%>
		</div>
	</div>
	<%= form.button "Schedule", data: { turbo: false }, class: "btn btn-primary" %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card mt-3 bg-light mb-3 mb-3">
	<div class="card-body">
		<h5 class="card-title">Tweet</h5>
		<p class="card-text">	<%= tweet.body %> </p>
	</div>
	<div class="d-flex justify-content-between card-footer">
		<div class ="text-start">
			<img src="<%= tweet.twitter_account.image %>" class = "rounded-circle img-thumbnail">
			<%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
			<div>
			</div>
			<div class="text-end">
				<% if tweet.published? %>
					<%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
				<% else %>
					<div> Scheduled for: <%= l tweet.publish_at, format: :long %>
						<%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/tweets/edit.html.erb
<h2>Edit Scheduled Tweet</h2>
<%= render "form_edit", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class = "d-flex justify-content-between align-items-center">
	<h2> Your Tweets My Dear</h2>
	<% if Current.user.twitter_accounts.any? %>
		<%= link_to "Schedule Tweets", new_tweet_path, class: "btn btn-primary" %>
	<% end %>
</div>
<div class = "container">
	<% if Current.user.twitter_accounts.none? %>
		<%= link_to "Connect Your Twitter Account My Very Best", "/auth/twitter", class: "btn btn-primary" %>
	<% end %>
</div>
<%= render @tweets %>

app/views/tweets/new.html.erb
<h2> Schedule a Tweet Earthling! </h2>
<%= render "form_schedule", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
	<h2>Twitter Accounts</h2>
	<%= link_to "Connect a Twitter Account", "auth/twitter", method: :post, local:true, data: { turbo: false }, class: "btn btn-primary" %>
</div>
<% @twitter_accounts.each do |twitter_account| %>
	<div class="me-4">
		<div class="d-flex align-items-center mb-4">
			<img src="<%= twitter_account.image %>" class = "rounded-circle">
			<%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
		</div>
		<%= button_to "Disconnect Your Account", twitter_account, method: :delete, form: { data: { turbo_confirm: 'Are You Brave Enough?' } }, class:"btn btn-danger" %>
	</div>
<% end %>